### ISSUE TITLE
IST generates generic_type field with value ffffffffffffffff

### ISSUE THREAD

**Issue by janhybs** [flow123d/flow123d#1026]
When generating `input_reference.json` file for purposes of generating `tex` or `html` doc, all input types (except `SELECTION`) have `generic_type` field set to `ffffffffffffffff`. This issue is related to #1006 

```yaml
- id: 27fe8493bd28f582
  input_type: Record
  name: Root
  generic_type: ffffffffffffffff
  attributes: {}
  description: Root record of JSON input for Flow123d.
```

There is temp fix #1025 which I think should not be permanent as it may lead to potential problems in the future.

[input_reference.yaml.txt](https://github.com/flow123d/flow123d/files/2610535/input_reference.yaml.txt)
