### ISSUE TITLE
Split boundary conditions for mechanics

### ISSUE THREAD

**Issue by jstebel** [flow123d/flow123d#1296]
In mechanics, there are 2 basic types of b.c. - displacement and traction. Sometimes it is however necessary to use different type for normal and tangential direction. In 2D and 1D in addition we have 1 or 2 directions that are neither normal to the boundary nor tangential (aligned with the 2D or 1D element). Summing up, we should provide possibility to set independent type for up to 3 directions (I call them normal, tangent and binormal as in the Frenet frame).

Consider for example the "roller" b.c. on the bottom side of a square domain in XY plane: We want zero displacement in Y direction (normal), zero traction in X direction (tangent) and, in addition, zero displacement in Z direction (binormal). Currently, the "displacement_n" condition would lead to zero traction in Z direction.

Proposal: Extend the "bc_type" to a record with 3 keys normal, tangent, binormal. Example:

```
bc_type:
  normal: displacement
  tangent: traction
  binormal: displacement

bc_displacement: [ dx, dy, dz ]
bc_traction: [ tx, ty, tz ]
```

The bc_displacement and bc_traction fields are common and only their projection to the particular direction is used.
