### ISSUE TITLE
Unit scaling of fields does not work.

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1495]
Having `bc_flux` of the DG transport is given by a formula that depends on user fields. The specification of the unit has no effect.
In particular setting the unit to: 

- `kg*m*md/y`
- `kg*m*md/s`
- None

has no effect on the mass total influx according to the mass_balance output. 
Could be problem in combination of user fields and units.

User fields have missing support for units.

```
     user_fields:
        - name: bc_flux_x
          is_boundary: true
          scalar_field: !FieldFormula
            value: if((x > 12)and(x < 16),1.0,0.0)
        - name: bc_flux_t
          is_boundary: true
          scalar_field: !FieldTimeFunction
            time_function:  # conc_flux_UOS_[kg:y]
              values: !include_csv
                file: /home/jb/workspace/Endorse/tests/sandbox/full_transport_101/conc_flux_UOS_[kg:y].csv
                separator: ","
                n_head_lines: 1
                format:
                  t:
                    time: $0
                  value: $1

      input_fields:
        - region: [.box_boreholes, .fr_bore]
          bc_type: total_flux
          bc_flux: !FieldFormula
            value: bc_flux_x * bc_flux_t * 0.1
            unit: kg*m*md/s # kg*m*md/y
```
