### ISSUE TITLE
Integration death tests

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#744]
- [x] Add support for death tests in runtest (so that the test does not fail if execution fails).
- [ ] Implement new checking rule for integration tests that search for an regexp in given file.

---

- [x] Make first three integration death tests: e.g. missing file, missing field, some time error
- [ ] (later) Make integration tests leading to all errors detected out of the input subsystem. The list of exceptions is attached.

**Comment by dflanderka** [comment]
Candidate to add as death integral tests:

  - Wrong value ... of the Selection
    - type of exception **ExcInputError**
    - unknown descendant of Abstract (wrong record name), or wrong value in selection
  - Missing obligatory key ...
    - type of exception **ExcInputError**
    - undefined obligatory key in Record
  - Can not determine type of the Abstract
    - type of exception **ExcInputError**
    - missing descendant if autoconversion is not allowed, typically in transport
  - Do not fit the size ... of the Array
    - type of exception **ExcInputError**
    - value is out of limits
  - Value out of bounds.
    - type of exception **ExcInputError**
    - for Integer or Double
  - invalid data type in IST
    - catch **YAML::Exception**, throw **ExcInputError**
    - unexpected type on input (e. g. String instead of some numerical type)

**Comment by jbrezmorf** [comment]
Need some naming system since there will be lot of tests...

**Comment by x3mSpeedy** [comment]
@jbrezmorf @dflanderka Added regex option in config.yaml file 4a5bc1a1b7b7480fe677539af2c33fee759265e0

Now you are able to specify rules to check specific errors. See config.yaml below:

```yaml
test_cases:
- files: 01_unsteady.yaml
  death_test: true
  check_rules:
    - regex:
        files: [job_output.log]  # file must exists in ref_out folder!
        substr: "Missing the key 'time', obligatory for the transient problems."
    - regex:
        files: [job_output.log]  # same file can be checked several times
        regex: "Program [Ee]rror: Violated assert!"

```
`job_output.log` is redirected output of the flow123d so in this file you can search for specific `substr`ings or `regex`es.

Make sure to create dummy `job_output.log` in `ref_out` folder to trigger check rule.
