### ISSUE TITLE
yaml parser bug

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#869]
YAML parser used in Flow123d fails for a correct YAML file with unusual indention of a comment.

Input file:
[01_1d.yaml.txt](https://github.com/flow123d/flow123d/files/1260058/01_1d.yaml.txt)

Error message:
```
  User Error: Error in input file: '/opt/flow123d/flow123d/tests/14_darcy_richards/01_1d.yaml' at address: '/problem/flow_equation/time/init_dt'
    ##                   The value should be 'YAML real', but we found: 
    ##                   YAML type: 'other scalar type'
```

**Comment by dflanderka** [comment]
YAML parser fails correctly. Case in input file is not comment, but it's multiline string. See example:

```
root:
  key_a: some text
    on more than one line
    can contain # comment pattern inside the line
    # or at begining of the line
  key_b: 42
    # is multiline string too
```

Correct comments must be entered thus:

...
root:
  # description of key_a on separate line
  key_a: 10
  key_b: 20 # or on same line as key_b declaration
  
...
